name: 'Build windows'

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        mode: [releasedbg]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v2

    - name: 'Checkout submodules'
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1

    - name: 'Cache xmake dependencies'
      uses: actions/cache@v4
      with:
        path: ~/AppData/Local/.xmake/packages
        key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
        
    # Install xmake
    - name: 'Setup xmake'
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: 2.9.5
        actions-cache-folder: '.xmake-cache' # This doesn't cache dependencies, only xmake itself
        actions-cache-key: ${{ matrix.os }}

    - name: 'Configure xmake and install dependencies'
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --vs_sdkver=10.0.19041.0 --yes -vD

    # Build the game
    - name: 'Build with xmake'
      run: xmake -y

    # Install node
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 'Generate build'
      run: xmake install -o distrib

    - name: 'Package build'
      run: xmake pack

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/xpack/Cyberpunk Multiplayer/Artifacts.zip

    
    
      
